# This is a basic workflow to help you get started with Actions
#

- name: PyInstaller Windows
# You may pin to the exact commit or the version.
# uses: JackMcKew/pyinstaller-action-windows@a8dee21ad01bbc7e7363d445bb632691b95ba057
  uses: JackMcKew/pyinstaller-action-windows@v0.1.2
  with:
    # Directory containing source code (optional requirements.txt).
    path: # default is src
    # Specify a custom URL for PYPI
    pypi_url: # optional, default is https://pypi.python.org/
    # Specify a custom URL for PYPI Index
    pypi_index_url: # optional, default is https://pypi.python.org/simple
    # Specify a file path for .spec file
    spec: # optional, default is 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
  
    strategy:
      matrix:
        python-version: [3.9]
    # The type of runner that the job will run on
    runs-on: windows

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
              pip install pyinstaller
              pip install -r requirements.txt
              pyinstaller --onefile bannoti.py
              
